default:
  use_ycrcb: False
  seginit:
    type: random
    radius: 5
  save:
    init: true
    image: true
    output: true
    video: false
    loss: false
  trainable: 
    bg: False
    record: True
    stroke: False
#  num_segments: 8
  num_iter: 500
  lr_base:
    bg: 0.01
    point: 1
    color: 0.01
    stroke_width: null
    stroke_color: null
  coord_init:
    type: sparse
  seed: 0
  loss:
    use_l1_loss: false
    use_distance_weighted_loss: true
    xing_loss_weight: 0.01
    bis_loss_weight: null

experiment_1x1:
  path_schedule:
    type: repeat
    max_path: 1
    schedule_each: 1

experiment_8x1:
  path_schedule:
    type: repeat
    max_path: 8
    schedule_each: 1

experiment_16x1:
  path_schedule:
    type: repeat
    max_path: 16
    schedule_each: 1

experiment_32x1:
  path_schedule:
    type: repeat
    max_path: 32
    schedule_each: 1

experiment_1357:
  path_schedule:
    type: list
    schedule: [1, 3, 5, 7]

experiment_exp2:
  path_schedule:
    type: exp
    base: 2
    max_path: 200
    max_path_per_iter: 32

experiment_200list:
  path_schedule:
    type: list
    schedule: [1,3,3,3,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5]



experiment_exp2_64_8:
  path_schedule:
    type: exp
    base: 2
    max_path: 64
    max_path_per_iter: 8


# for comparison
experiment_exp2_8:
  path_schedule:
    type: exp
    base: 2
    max_path: 8
    max_path_per_iter: 32

experiment_exp2_16:
  path_schedule:
    type: exp
    base: 2
    max_path: 16
    max_path_per_iter: 32

experiment_exp2_32:
  path_schedule:
    type: exp
    base: 2
    max_path: 32
    max_path_per_iter: 32

experiment_exp2_64:
  path_schedule:
    type: exp
    base: 2
    max_path: 64
    max_path_per_iter: 32

experiment_exp2_128:
  path_schedule:
    type: exp
    base: 2
    max_path: 128
    max_path_per_iter: 32

experiment_exp2_256:
  path_schedule:
    type: exp
    base: 2
    max_path: 256
    max_path_per_iter: 32

experiment_exp2_512:
  path_schedule:
    type: exp
    base: 2
    max_path: 512
    max_path_per_iter: 64

experiment_list_64:
  path_schedule:
    type: list
    schedule: [1, 3, 4, 8, 16, 32]


experiment_list_512:
  path_schedule:
    type: list
    schedule: [1, 3, 4, 8, 16, 32, 64, 64, 64,64, 64 ,64, 64]
