default:
  use_ycrcb: False
  seginit:
    type: circle
    radius: 5
  save:
    init: true
    image: true
    output: true
    video: true
    loss: false
  trainable: 
    bg: False
    record: True
    stroke: False
#  num_segments: 16
  num_iter: 600
  lr_base:
    bg: 0.01
    point: 1
    color: 0.01
    stroke_width: null
    stroke_color: null
  coord_init:
    type: sparse
  seed: 0
  loss:
    use_l1_loss: true
    use_distance_weighted_loss: false
    xing_loss_weight: 0.01
    bis_loss_weight: null

experiment_16x1:
  path_schedule:
    type: repeat
    max_path: 16
    schedule_each: 1

experiment_32x1:
  path_schedule:
    type: repeat
    max_path: 32
    schedule_each: 1

experiment_1357:
  path_schedule:
    type: list
    schedule: [1, 3, 5, 7]

experiment_exp2:
  path_schedule:
    type: exp
    base: 2
    max_path: 200
    max_path_per_iter: 32

experiment_200list:
  path_schedule:
    type: list
    schedule: [1,3,3,3,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5]
