default:
  use_ycrcb: False
  seginit:
    type: circle
    radius: 50
  save:
    init: false
    image: false
    output: true
    video: true
    loss: false
  trainable: 
    bg: False
    record: True
    stroke: False
#  num_segments: 8
  num_iter: 500
  lr_base:
    bg: 0.01
    point: 1
    color: 0.01
    stroke_width: null
    stroke_color: null
  coord_init:
    type: sparse
  seed: 0
  loss:
    use_l1_loss: false
    use_distance_weighted_loss: true
    xing_loss_weight: 0.
    bis_loss_weight: null




experiment_exp2_256:
  path_schedule:
    type: exp
    base: 2
    max_path: 256
    max_path_per_iter: 48
