default:
  use_ycrcb: False
  seginit:
    type: circle
    radius: 5
  save:
    init: true
    image: true
    output: true
    video: true
    loss: false
  trainable: 
    bg: False
    record: True
    stroke: False
#  num_segments: 8
  num_iter: 500
  lr_base:
    bg: 0.01
    point: 1
    color: 0.01
    stroke_width: null
    stroke_color: null
  coord_init:
    type: sparse
  seed: 0
  loss:
    use_l1_loss: false
    use_distance_weighted_loss: false
    xing_loss_weight: 0.01
    bis_loss_weight: null

experiment_1x1:
  path_schedule:
    type: repeat
    max_path: 1
    schedule_each: 1

experiment_8x1:
  path_schedule:
    type: repeat
    max_path: 8
    schedule_each: 1

experiment_2x1:
  path_schedule:
    type: repeat
    max_path: 2
    schedule_each: 1


experiment_exp2_512:
  path_schedule:
    type: exp
    base: 2
    max_path: 512
    max_path_per_iter: 64
